apiVersion: batch/v1beta1
kind: CronJob
metadata:
  name: operation-carlife-order-job
spec:
  schedule: "10 1 * * *"
  jobTemplate:
    spec:
      template:
        spec:
          imagePullSecrets:
            - name: regsecret
          containers:
            - name: operation-carlife-order-job
              imagePullPolicy: Always
          restartPolicy: Never